# Generated by Django 3.2.5 on 2022-02-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commu', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='media_id',
            new_name='media',
        ),
    ]
