# Generated by Django 3.2.5 on 2022-02-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='no_nick_name', max_length=20),
        ),
    ]
