# Generated by Django 3.2.5 on 2022-02-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
